### ISSUE TITLE
Prepare DSE-oriented proposal to get on the same page with Neal Davies

### ISSUE THREAD

**Issue by davclark** [BIDS/sensor-group#19]
An initial document, maybe pulling in @dani-lbnl and @kevkoy to set a direction with the Moorea project. Part of this could be folded into the Siemens Proposal (#18).

**Comment by davclark** [comment]
This was sent off. Open a new issue for more work on this.

**Comment by postfalk** [comment]
Dav,

The last message was flagged as suspicious in my gmail account. Do you
thing that is something normal about git or is something else going on? I
just had to struggle with a Trojan yesterday.

Falk

On Wed, Mar 11, 2015 at 4:59 PM, Dav Clark notifications@github.com wrote:

> Closed #19.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
