### ISSUE TITLE
Agenda for Feb 25, 2015 Meeting

### ISSUE THREAD

**Issue by davclark** [BIDS/sensor-group#20]
1. Report out on work-in-progress
   1. pulling data from GitHub API (general HTTP+JSON interfaces)
   2. work towards dynamic visualizations
   3. state of purchasing / sensors
2. Plans for next week
   1. Whiteboard: overview of what we'll do with sensors (provide reading)
   2. Scheduling
3. Make sure everyone is on Slack, GitHub, etc.

**Comment by postfalk** [comment]
A little bit chaotic but the important terminology is there.

https://en.wikipedia.org/wiki/Sensor

For the application level it means to create a data model that can deal
with crazy states of  sensors. Malfunction seems to be the ideal event for
detection.

We could also think a little bit about state vs. change (event, activity).

Looking forward to this,
Falk

On Tue, Feb 24, 2015 at 5:38 PM, Dav Clark notifications@github.com wrote:

> 1. Report out on work-in-progress a. pulling data from GitHub API
>    (general HTTP+JSON interfaces) a. work towards dynamic visualizations a.
>    state of purchasing / sensors
> 2. Plans for next week a. Whiteboard: overview of what we'll do with
>    sensors (provide reading) a. Scheduling
> 3. Make sure everyone is on Slack, GitHub, etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS/sensor-group/issues/20.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by davclark** [comment]
From @smnmyr:

I wanted to get back to you about the topic of activity modeling: When you guys create activities to push to ASbase, I think it'd be a good idea to make everyone adhere to a process along these guidelines (more details here: http://dret.net/lectures/iot-spring15/rest from slide 34)
1. Try to use verbs and objects that are already defined in the activity schema, here http://activitystrea.ms/registry/verbs/
2. If that doesn't feel fully right (but approximately), try to use one of the defined verbs, but extend it. For our project, we've added a "subVerb" property that extends (but not hijacks!) the base verb
3. If it's just not possible to reuse an already defined verb without hijacking, create a new one (and document it!)

**Comment by davclark** [comment]
Falk will run PostgreSQL workshop during the Wed 10am time slot (around March 28th and April 4th)

Folks focusing on web viz can float to other meetings, for example, the Monday 3pm meeting.

**Comment by postfalk** [comment]
Should we close this now?
