### ISSUE TITLE
Agenda Tuesday 3/10: Arduino Xmas

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#21]
- Xmas - unpacking Arduinos and sensors
- Get LED 13 blinking (aka Arduino basics)
- Use other pins, introduction into C, Wire.h

**Comment by postfalk** [comment]
@davclark that is the agenda for tomorrow. Anything else we should talk about it, yes we are starting at 3pm.

**Comment by davclark** [comment]
I was pinging you because it wasn't on the calendar! For example, this means room C was not reserved. But on the upside, I reserved room B (B=big).

**Comment by postfalk** [comment]
Oh sorry, I did not update the calendar. I should copy all these things to
the glass-beads calendar.
Did you read about my success with the blue-tooth. I think the cheap
modules still need pairing but it can be easily done from Python.
I hope to get a chance to implement this tomorrow.

That is where I am at (requires still manual setup of the bluetooth
connection).
https://gist.github.com/postfalk/604d667da192a86d8534

In this code there is actually no bluetooth handling at all (except the
access to the serial socket). It just uses the serial that is layered on
top of it.

Falk

On Mon, Mar 9, 2015 at 12:00 PM, Dav Clark notifications@github.com wrote:

> I was pinging you because it wasn't on the calendar!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS/sensor-group/issues/21#issuecomment-77919433.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
https://learn.adafruit.com/photocells

**Comment by postfalk** [comment]
Here is the math

http://home.roboticlab.eu/en/examples/sensor/photoresistor

**Comment by postfalk** [comment]
https://en.wikipedia.org/wiki/I%C2%B2C
