### ISSUE TITLE
ASBase Queries All Failing

### ISSUE THREAD

**Issue by KishPatel1996** [BIDS/sensor-group#22]
We are having trouble querying information from the ASBase.  

Can someone check if this is an issue with the database, or are we using it improperly? 
@smnmyr  @davclark 

 **Here are some examples that we have tried, all of which are returning "request failed."** 
http://russet.ischool.berkeley.edu:8080/query?startTime=2015-02-24
http://russet.ischool.berkeley.edu:8080/query?startTime=2015-02-22&endTime=2015-02-24

We also tried advanced queries using the MongoDB language in JSON format.

**Comment by smnmyr** [comment]
Fixed. Thanks!

**Comment by dianecw** [comment]
Looks like all the queries are now returning
"{"totalItems":0,"@type":"http://activitystrea.ms/2.0/Collection","items":[]}". 

We've tried simple and advanced queries, by date and repository name etc.

**Comment by smnmyr** [comment]
Yes, the query http://russet.ischool.berkeley.edu:8080/query?startTime=2015-02-24 returns 0 items. I cannot find a mistake, however. Did you put activities into the DB with a startTime > 2015-02-24?

I can find your uploads using the query `POST http://russet.ischool.berkeley.edu:8080/query`
and contents `Content: { "verb" : { "$in" : [ "issue" ] } }`

**Comment by dianecw** [comment]
Great, I think I got it working. Thanks for your quick responses!
