### ISSUE TITLE
Please add documentation how to install access token in external file.

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#26]
You could move your work into a folder (and eventually to its own repo) and at a README.md file.

**Comment by KishPatel1996** [comment]
Added README

**Comment by postfalk** [comment]
@KishPatel1996 Do you think this one could be closed? Go ahead if you think so.

**Comment by davclark** [comment]
Actually, in your commit message (in the future), you can add, e.g., "closes #26" and GitHub will auto-close the issue and refer to the commit.

**Comment by KishPatel1996** [comment]
Ah, didn't know that.  Definitely will come in handy.  

I'll close it.
