### ISSUE TITLE
Doc strings are usually placed underneath the first line of a function/class declaration

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#29]
``` python

def some_function():
     """This function does nothing."""
     pass
```

From this documentation and even unit tests can be generated automatically. You could stuff your entire documentation text there (which is only feasible for smaller projects.) See https://www.python.org/dev/peps/pep-0257/

**Comment by davclark** [comment]
What is the issue-tracker label for? Maybe we should have a wiki page about our labelling conventions?

**Comment by postfalk** [comment]
issue-tracker is for the actual github-issue-tracker, people are working
on. We are getting in some self-referential problems here. For this reason
we should move actual software in a different repo.

Falk

On Fri, Mar 6, 2015 at 1:08 PM, Dav Clark notifications@github.com wrote:

> What is the issue-tracker label for? Maybe we should have a wiki page
> about our labelling conventions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS/sensor-group/issues/29#issuecomment-77636127.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by KishPatel1996** [comment]
This issue was moved to glass-bead-labs/data-connector#2
