### ISSUE TITLE
Basic supplies

### ISSUE THREAD

**Issue by davclark** [BIDS/sensor-group#3]
- [x] ask whether we could use one of the little fish bowls as a hacker station (which can be still used for other things but will hold a modest amount of stuff - at home I get away with three boxes)
- [x] scope / get some basic supplies

**Comment by postfalk** [comment]
_BASIC SUPPLIES_

A small collection of products:
- very basic
  contains soldering basics, basic tools (wire cutters etc.), some wire http://www.adafruit.com/product/136
  https://www.sparkfun.com/products/13087
- somewhat advanced
- advanced
- other must haves
  starter kit parts, https://www.sparkfun.com/products/10003
  resistors, https://www.sparkfun.com/products/10969
  breadboards, https://www.sparkfun.com/products/12002
  wires, https://www.sparkfun.com/products/124
  wires, http://www.adafruit.com/products/153
  arduino starter kit (one will not hurt), https://www.adafruit.com/products/68
- bluetooth shields for arduino
  http://www.adafruit.com/products/1628
- sensors
  I2C pressure, temperature, http://www.adafruit.com/products/1603
- server

**Comment by postfalk** [comment]
We decided to create a shopping list not exceeding $1000. Kevin gave green light.

**Comment by postfalk** [comment]
@davclark Schedule work meeting for finalizing list in BearBuy. Next week? After some more research.

**Comment by davclark** [comment]
Generally, if my calendar is free, you are welcome to book it. I think this
should be doable in about an hour.

**Comment by dani-lbnl** [comment]
Can we add some more stuff:
- soldering metal (white soldering, lead free?) and the solder
- batteries
- pliers and wire cutters (if not as part of any starter kit, usually not)
  thx
  Dani

Best Regards,

## Dani

Daniela Ushizima, PhD.
Head Deputy of the Visualization Group
Research Scientist, Lawrence Berkeley National Lab.
BIDS Data Scientist, University of California, Berkeley
1 Cyclotron Road MS 1650
Berkeley, CA 94720
lab: +1 510 486-4061
dushizima@lbl.gov

**Comment by postfalk** [comment]
@dani-lbnl Does this look sufficient for a first pass: http://www.adafruit.com/product/136? If not make a or more wishes.

**Comment by postfalk** [comment]
They are ordered. Issue will be closed when they arrive :+1:

**Comment by davclark** [comment]
@davclark and @postfalk need to follow up with suppliers to see where still-unrecieved packages are.
