### ISSUE TITLE
Agenda Tuesday 3/17: Dashboard

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#30]
Create first version of a dashboard

**Comment by postfalk** [comment]
Hi, 

... a quick update on the Agenda. I did not succeded in creating a very good project structure for the data collector yet. I am still experimenting with a setup over serial that allows for painless and automatic reconnecting, a timed measurement, and error reporting.

For tomorrow, we will work on the dashboard. I think we will mostly connect our d3 example to some real data from ASBase. That will be a lot of fun.

For anyone who would like to dash ahead, you could look at 

https://github.com/mbostock/d3/wiki/Requests

Don't get scared just scroll down to d3.json and remember callback functions that is all what is needed.

Something like request, reformat data, call update should get your data on the screen

Falk

**Comment by davclark** [comment]
Am I running this, or are you, @postfalk?

**Comment by postfalk** [comment]
I could run it or you could. I will be there. I could also just help with
the d3.js part and work on my serial part. My comment was more about what I
didn't do over the week and that we will be ok anyways.

What is your preference? I will be happy to lean back.

Falk

On Mon, Mar 16, 2015 at 9:31 PM, Dav Clark notifications@github.com wrote:

> Am I running this, or are you, @postfalk https://github.com/postfalk?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/glass-bead-labs/sensor-group/issues/30#issuecomment-82099614
> .

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by jesscxu** [comment]
http://russet.ischool.berkeley.edu:8080/query/?startTime=2015-02-24

**Comment by postfalk** [comment]
https://github.com/mbostock/d3/wiki/Requests

**Comment by postfalk** [comment]
http://bl.ocks.org/postfalk/f0d3ceddd49f0c6fa029

**Comment by postfalk** [comment]
https://decyborg.wordpress.com/2013/09/08/bluetooth-serial-communication-with-arduino-jy-mcu-bluetooth-and-macbook-pro/

**Comment by postfalk** [comment]
https://gist.github.com/postfalk/604d667da192a86d8534

**Comment by postfalk** [comment]
http://www.jeromecukier.net/blog/2011/08/11/d3-scales-and-color/
