### ISSUE TITLE
Agenda Friday 3/20: Requirements

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#31]
- discussing requirements for what we could achieve by the end of the semester
- review project structure
- create github repo

**Comment by postfalk** [comment]
Quick check-in: Is everyone ok with the fact that this very important session is during spring break or should we move it?

**Comment by dianecw** [comment]
I'll be home for spring break (3/21-3/29), so I won't be able to make it. Could this meeting be moved earlier? Even though I'll be home, I'll be spending most of my time working so it'd be great to have things to work on over break.

**Comment by postfalk** [comment]
What about Friday 3/20 in parallel to the Tai Chi group (2pm-5pm). Cannot
confirm yet (depends on the Postgres intro).

On Fri, Mar 6, 2015 at 10:58 AM, Diane Wang notifications@github.com
wrote:

> I'll be home for spring break (3/21-3/29), so I won't be able to make it.
> Could this meeting be moved earlier? Even though I'll be home, I'll be
> spending most of my time working so it'd be great to have things to work on
> over break.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS/sensor-group/issues/31#issuecomment-77614874.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
Should we move this to 3/20 2pm to 4:45pm. I could confirm this time if everyone would be in board.

**Comment by dianecw** [comment]
This is fine with me, thank you!

**Comment by postfalk** [comment]
Let's see whether it works for @KishPatel1996 and @jesscxu as well. And confirm next week.

**Comment by jesscxu** [comment]
That is fine with me too!

**Comment by KishPatel1996** [comment]
I have a flight from SFO at 9:30pm on the 20th.  2 to 4:45 should be fine.

**Comment by postfalk** [comment]
virtualenv -p /usr/bin/python3 env

**Comment by postfalk** [comment]
https://ecoengine.berkeley.edu/

**Comment by postfalk** [comment]
@jesscxu Are you still planning on coming in today? I just would like to now and decide where to work today. There is a lot of stuff going on at BIDS.

**Comment by jesscxu** [comment]
I figured out the problem I had earlier, so I won't be coming in today!

**Comment by postfalk** [comment]
Ok, thanks. Enjoy spring break.

On Tue, Mar 24, 2015 at 11:16 AM, Jessica Xu notifications@github.com
wrote:

> I figured out the problem I had earlier, so I won't be coming in today!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/glass-bead-labs/sensor-group/issues/31#issuecomment-85628940
> .

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
