### ISSUE TITLE
Add Slack Integration

### ISSUE THREAD

**Issue by KishPatel1996** [BIDS/sensor-group#34]
add slack integration so that the new comments are posted onto ASBase.

Also look into creating a slackbot just for fun

**Comment by KishPatel1996** [comment]
There may be a slight problem with using Slack's API.  It seems that Slack uses timestamps instead of, well, normal time format.  Each timestamp is independent of other channels.  They only offer insight into the channel it originated from.  

ie: 1359414002.000003 is a timestamp.

**Comment by davclark** [comment]
I added a question here: https://github.com/slackhq/slack-api-docs/issues/7

**Comment by KishPatel1996** [comment]
wonderful, thanks
