### ISSUE TITLE
4/14/2014 Agenda

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#45]
Hey Dav,

Could you take the lead tomorrow to get everyone (including me) started on the server and on MongoDB? Then we could discuss our json schema for the DB in the rest of the time. I am trying to advance the serial protocol question between Arduino and Computer. I also got the Raspi prototype shields.

@KishPatel1996 @dianec @jesscxu maybe you guys could join this discussion what we need to do tomorrow in order to keep 5things moving. I think the overarching topic is still tying everything together. 

On this note, I will be out on Wednesday morning for a dentist appointment. Dav do you wanna use the time with our students?

**Comment by davclark** [comment]
Sounds good!

We'll cover the following. Feel free to add questions below:
- Getting onto the server
- accessing mongo from python
- Structure of mongo queries (you know this?)
- Efficiency concerns
