### ISSUE TITLE
Where can I review/edit poster content?

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#48]
@davclark Did you start this? Or should I create content using Markdown for now? Sorry for not listening?

**Comment by davclark** [comment]
I haven't started this. I think this repo is a reasonable place to put things. We can also commit the SVG from Inkscape / Illustrator here. Github has nice SVG diffing capabilities.

**Comment by postfalk** [comment]
Sounds great.

On Thu, Apr 30, 2015 at 8:49 AM, Dav Clark notifications@github.com wrote:

> I haven't started this. I think this repo is a reasonable place to put
> things. We can also commit the SVG from Inkscape / Illustrator here. Github
> has nice SVG diffing capabilities.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/glass-bead-labs/sensor-group/issues/48#issuecomment-97846454
> .

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
