### ISSUE TITLE
Address privacy concerns/develop policies

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#5]
Since we are moving on this, I heard some concerns recently. I think we should take following steps:
- [x] discuss among BIDS fellows
- [ ] ~~develop policy~~
- [ ] ~~design signs that makes people aware of every sensor, what they do, and collect~~
- [ ] make data streams public (?), paradox: if we could make them public, privacy will be met
- [ ] ~~create repo where people can address concerns as GitHub issues~~

**Comment by postfalk** [comment]
At our today's, fellow meeting we came to the conclusion that there is only very limited support for automatically collecting data on the use of the BIDS space in DOE 190. Fellows suggested all kinds of well-thought-out policies to deal with these issues. 

However, me (@postfalk) and @davclark do not have the capacity to work and implement such procedures and we doubt that they will make people happy in the end.

For this reason we decided to focus on environmental sensing outside of DOE190.

**Comment by davclark** [comment]
I'm going to propose a privacy / policy / ethics session this semester in the Tech4Measurement seminar I'll be organizing w/ the Social Science Matrix this year (we're having a planning lunch next Wednesday at 12:30 if you'd like to join). I'm going to call this essentially migrated off of our development path. Re-open if you'd like to continue the conversation here!
