### ISSUE TITLE
Things to learn for sensing

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#8]
In our small sensor project, we will explore the entire path from sensing physical characteristics, cleaning, storing, processing data through a network of servers, eventually making sense of data, and deliver content to web users.

The Siemens Network of Things Research Group will help us and we would like to implement parts of their [Activity Stream](http://en.wikipedia.org/wiki/Activity_stream) based platform.

**Actual Sensor Streams from Berkeley's Hydrowatch Observatory**
- http://sensor.berkeley.edu/ (read directions on how to log on as a guest)

**SIEMENS' activity stream platform**
- http://russet.ischool.berkeley.edu:8080/webresources/apidoc/

**OS**
- [Ubuntu](https://openwrt.org/)/[Debian](https://www.debian.org/) 
- [OpenWrt](https://openwrt.org/) - a lightweight Linux distribution for devices 
- smaller more embedded Debian versions, e.g. Raspbian

Master the command line since you will communicate a lot with remote devices using SSH

**Microcontrollers**
- [Arduino](http://arduino.cc/)
- [Raspberry PI](http://www.raspberrypi.org/)
- TinyOS (runs on Arduino!?)

**Networking**
- Wifi
- Bluetooth
- Ethernet

**Coding**
- Python
- some C (without any ++ or #), however the Wire.h and the Arduino derivatives provide some easy higher level functionality to deal with Microcontrollers

**Protocols**
- http
- [I2C](https://learn.sparkfun.com/tutorials/i2c)

**Databases**
- [SQLite](http://www.sqlite.org/)

**Framework and Concepts**
- ORM
- RESTful APIs, [the classic dissertation by Roy Fielding](http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm), and for starters [here](http://en.wikipedia.org/wiki/Representational_state_transfer)
- [Morepath](http://morepath.readthedocs.org/en/latest/) (Python web framework, WSGI application)

**Provisioning and Deployment**
- [Ansible](http://docs.ansible.com/) 
- SSH
- Web and Reverse Proxy Server ([Nginx](http://wiki.nginx.org/Main))

**Frontend**
- JavaScript
- [OnsenUI](http://onsen.io/)
- [d3.js](http://d3js.org/) - see https://github.com/glass-bead-labs/static-c3
- [HTML5 websocket for realtime connections](http://www.websocket.org/)

**Campus Security Policies**

[Minimum Security Standards for Networked Devices (MSSND)](https://security.berkeley.edu/mssnd)

**Mobile devices**
- to get started quickly on Android: [MIT app inventor](http://appinventor.mit.edu/explore/)

**and of course SENSORS**

**Things we might explore together**
- [Autobahn](http://autobahn.ws/js/)
- Open Sensor framework for Android: [funf](http://www.funf.org/)
- Open Framework for clinical data: [Open mhealth](http://www.openmhealth.org/)
- Versatile data collection service that supports real time streaming and data archival: [GATD](https://github.com/lab11/gatd)
- [Data Sensing Lab](http://datasensinglab.com/)
  *[Kinoma Create](http://kinoma.com/create/): Prototyping framework for IoT devices, currently used in CS160
- http://docs.spacebrew.cc/
- http://postscapes.com/internet-of-things-protocols

**Terms**
- multi-hop network

**Standards**
- [Observation Data Model](http://his.cuahsi.org/odmdatabases.html)
- [Data Turbine](http://www.dataturbine.org/)

**Comment by davclark** [comment]
Looking at David Culler's site, and cross-correlating with my work on my own raspberry pi stuff, I found this in Lua:

http://eclipse.org/mihini/

I'm thinking lua might be a really good choice for us.

**Comment by postfalk** [comment]
I am not sure whether we should add Lua. Makes it more complex and I am not
really fond of it. Works well on very small devices (and is part of
OpenWrt) but I am not sure whether our use case actually applies since the
Arduino UNO does not run an embedded Linux (Arduino Yun does) and we have a
full grown computer as gateway device. But of course we could tinker around
with it. But if you want to use a framework that already exists go for it.

Falk

On Tue, Mar 24, 2015 at 9:59 PM, Dav Clark notifications@github.com wrote:

> Looking at David Culler's site, and cross-correlating with my work on my
> own raspberry pi stuff, I found this in Lua:
> 
> http://eclipse.org/mihini/
> 
> I'm thinking lua might be a really good choice for us.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/glass-bead-labs/sensor-group/issues/8#issuecomment-85837302
> .

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
