### ISSUE TITLE
Do you have an empty ansible project structure we could bootstrap?

### ISSUE THREAD

**Issue by postfalk** [BIDS/sensor-group#9]
Otherwise I will create or find one in the next few days.
Falk

**Comment by davclark** [comment]
If you give me a plain English description, I'm happy to make a playbook. I
only have a playbook for installing data science tools.

**Comment by postfalk** [comment]
I think about a proven expandable folter structure. But that seems not be
too hard to create from the docs. Just lazy to retype everything. I can
take care of this.
Falk

On Tue, Feb 10, 2015 at 2:23 PM, Dav Clark notifications@github.com wrote:

> If you give me a plain English description, I'm happy to make a playbook. I
> only have a playbook for installing data science tools.
> On Feb 10, 2015 1:21 PM, "Falk Schuetzenmeister" <notifications@github.com
> 
> > wrote:
> > 
> > Assigned #9 https://github.com/BIDS/space-hackers/issues/9 to
> > @davclark
> > https://github.com/davclark.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/BIDS/space-hackers/issues/9#event-233536605.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BIDS/space-hackers/issues/9#issuecomment-73797265.

## 

Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility http://gif.berkeley.edu/

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by davclark** [comment]
Just start with everything in one big file! It's easy to refactor as things
get larger.
